language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

script:
  - docker compose run app python manage.py test && flake8
